apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployguard.fullname" . }}-secret
  labels:
    {{- include "deployguard.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: "{{ $value }}"
  {{- end }}