apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployguard.fullname" . }}-svc
  labels:
    {{- include "deployguard.labels" . | nindent 4 }}
spec:
  # type: ClusterIP
  type: {{ .Values.service.type }} #changing it in values.yaml will break app so hardcoding it
  ports:
    - port: 8000
    # - port: {{ .Values.service.port }}  #changing it in values.yaml will break app so hardcoding it
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "deployguard.selectorLabels" . | nindent 4 }}
