apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployguard
  template:
    metadata:
      labels:
        app: deployguard
    spec:
      containers:
      - name: deployguard
        image: tehseen45/deployguard:v0.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            memory: "256Mi"
        ports:
          - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
          - name: DB_HOST
            value: postgres-service

          - name: DB_NAME
            value: deployguard
        envFrom:
          - configMapRef:
              name: deployguard-config
          - secretRef:
              name: deployguard-secret