apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployguard
  template:
    metadata:
      labels:
        app: deployguard
    spec:
      containers:
      - name: deployguard
        image: tehseen45/deployguard:v0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000